apiVersion: v1
kind: Service
metadata:
  name: kmemgraph
spec:
  selector:
    app.kubernetes.io/name: kmemgraph
  ports:
    - protocol: TCP
      name: "7474"
      port: 7474
      targetPort: 7474
    - protocol: TCP
      name: "3000"
      port: 3000
      targetPort: 3000
