apiVersion: v1
kind: Service
metadata:
  name: memgraph
spec:
  selector:
    app: memgraph
  type: NodePort
  ports:
    - protocol: TCP
      name: "7474"
      port: 7474

    - protocol: TCP
      name: "3000"
      port: 3000

    - protocol: TCP
      name: "7687"
      port: 7687
